### ISSUE TITLE
GAE provider not working

### ISSUE THREAD

**Issue by JanMikes** [tmaier/docker-dpl#1]
Hi, i tried your image for our gitlab-ci job to deploy, unfortunately it failed.

Here is full log:
```
Running with gitlab-ci-multi-runner 9.5.1 (96b34cc)
  on docker-runner-4gb-fra1-01 (da650b8a)
Using Docker executor with image tmaier/dpl:latest ...
Using docker image sha256:0943de4693b58438b9fbe1d6b8c49eef9eb48b4b24cf75969d1a5cbc096675db for predefined container...
Pulling docker image tmaier/dpl:latest ...
Using docker image tmaier/dpl:latest ID=sha256:faf38bc4c136e10a0e0f04ed8fef54d4fc73ffffdf5b32f71fad3ae46f479a28 for build container...
Running on runner-da650b8a-project-6383952-concurrent-0 via docker-runner-4gb-fra1-01...
Fetching changes...
HEAD is now at ce6d256 New deploy
From https://gitlab.com/entrydo/ticket-code
   ce6d256..2aea1f3  master     -> origin/master
Checking out 2aea1f3f as master...
Skipping Git submodules setup
$ dpl --provider=gae
Installing deploy dependencies
Successfully installed dpl-gae-1.9.5
1 gem installed

!!! Google App Engine support is experimental !!!

Python 2.7 Version
sh: bash: not found
Could not use python2.7
ERROR: Job failed: exit code 1
```

**Comment by tmaier** [comment]
You are right... 

There are three options

1)
We install all possible dependencies of all dpl providers

Pros:
- simple

Cons:
- complex to maintain (how to install all necessary dependencies easily?)
- large image


2)
We provide for each provider a dedicated docker tag and a dedicated image

Pros:
- smaller images
- provide new provider on-demand

Cons:
- many docker images to support

3)

You install the necessary dependencies on-demand in your .gitlab-ci.yml

Pros:
- no maintenance effort here

Cons:
- all the advantages of having a prepared image is gone
- ci build need longer

What do you think?

**Comment by tmaier** [comment]
Closing this ticket
